config/routes.rb
Whiteboard::Application.routes.draw do
  root to: 'homes#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :customers, only: %w[new create]
  resources :plans, only: %w[index]
  resources :subscriptions, only: %w[create destroy]
  resources :whiteboards, only: %w[index create update show]
  resources :pusher, only: %w[] do
    collection { post :auth }
  end
  resource :subscribers, only: %w[show] do
    collection { post :add_user }
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_user!

  def new
  end

  def create
    current_user.subscriber = Subscriber.create!
    current_user.stripe_card_token = params[:customer][:stripe_card_token]
    if current_user.save_stripe_customer
      flash[:analytics] = "/vp/add_credit_card"
      redirect_to plans_url, :notice => "Your billing information was updated."
    else
      flash.now[:alert] = "There was a problem with your credit card.  Please check your information."
      render :new
    end
  end
end

app/views/customers/new.html.erb
<div class="page-header">
  <h1>Billing Information</h1>
</div>
<div class="well span-7 offset-1">
  <div class="alert alert-info">
    <p>We take payment security seriously.</p>
    <p>Your credit card information is directly processed by our payment provider with bank level encryption and never touches our servers.</p>
    <p>We accept Visa, American Express, MasterCard, Discover, JCB, or Diners Club.</p>
  </div>
  <h2>Credit Card Information</h2>
  <%= form_for :customer, url: customers_url, id: "new_customer" do |f| %>
    <%= f.hidden_field :stripe_card_token %>
  <div id="stripe_error" class="alert alert-error hide">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
  <div class="input-prepend">
      <%= label_tag :card_number, "Credit Card Number" %>
      <span class="add-on"><i class="icon-lock"></i></span><%= text_field_tag :card_number, nil, name: nil %>
  </div>

  <div class="input-prepend">
    <%= label_tag :card_code, "Security Code on Card (CVC)" %>
    <span class="add-on"><i class="icon-lock"></i></span><%= text_field_tag :card_code, nil, name: nil %>
  </div>

  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
  </div>
<hr/>
<h2>Billing Information</h2>
  <div class="input-prepend">
    <%= label_tag :full_name, "Full Name as it appears on card" %>
    <span class="add-on"><i class="icon-lock"></i></span><%= text_field_tag :full_name, nil, name: nil %>
  </div>
  <div class="input-prepend">
    <%= label_tag :address_zip, "Zip/Postal Code of Billing Address" %>
    <span class="add-on"><i class="icon-lock"></i></span><%= text_field_tag :address_zip, nil, name: nil %>
  </div>
  <hr/>
   <div class="actions">
     <%= f.submit "Add Credit card", id: "new_customer_submit", autocomplete: "off",  data: { "no-turbolink" => true, disable_with: "Processing..."} %>
   </div>
   <%- end -%>
 </div>