config/routes.rb
Whiteboard::Application.routes.draw do
  root to: 'homes#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :customers, only: %w[new create]
  resources :plans, only: %w[index]
  resources :subscriptions, only: %w[create destroy]
  resources :whiteboards, only: %w[index create update show]
  resources :pusher, only: %w[] do
    collection { post :auth }
  end
  resource :subscribers, only: %w[show] do
    collection { post :add_user }
  end
end

app/controllers/whiteboards_controller.rb
class WhiteboardsController < ApplicationController
  before_filter :authenticate_subscriber!
  before_filter :find_models

  def index
    if @subscription
      @whiteboards = @subscription.drawings.page(params[:page]).per_page(10)
    else
      flash[:alert] = "You are currently not in a subscription. Please contact your account administrator."
    end
  end

  def create
    @whiteboard = @subscription.drawings.new
    @whiteboard.canvas = Drawing.blank_canvas
    if @whiteboard.save
      redirect_to whiteboard_url(@whiteboard)
    else
      flash[:alert] = @whiteboard.errors.full_messages.first
      redirect_to whiteboards_url
    end
  end

  def update
    @whiteboard = @subscription.drawings.find(params[:id])
    @whiteboard.generate_image_from_canvas!(params[:image_data]) unless Rails.env.test?

    respond_to do |format|
      format.js
    end
  end

  def show
    @whiteboard = @subscription.drawings.find(params[:id])
  end

  private

  def find_models
    @subscriber = current_user.subscriber
    @subscription = @subscriber.subscription
  end
end

app/views/whiteboards/_whiteboard.html.erb
<% cache whiteboard do %>
  <%= link_to whiteboard_path(whiteboard), class: "whiteboard_thumbnail", data: { "no-turbolink" => true } do %>
    <%= cl_image_tag whiteboard.canvas_url(:thumbnail), width: "500", height: "250" %>
  <%- end -%>
<% end %>

app/views/whiteboards/index.html.erb
<% if @subscription.present? %>
  <div class="page-header center">
    <h1 class="inline mr15">Whiteboards
    <%= link_to "New Whiteboard", whiteboards_path, method: :post, data: { "no-turbolink" => true }, class: "btn btn-info inline" %>
    </h1>
  </div>
  <div class="center" id="whiteboards">
    <% cache @whiteboards do %>
      <%= render partial: "whiteboards/whiteboard", collection: @whiteboards %>
    <% end %>
  </div>
  <div class="center">
    <%= will_paginate @whiteboards %>
  </div>
<% end %>

app/views/whiteboards/show.html.erb
<div id="canvas_save" class="alert alert-info">
  Saving...
</div>

<div class="center canvas_navbar">
    <%= link_to "Pen", "", class: "btn", data: { behavior: "pen_tool" } %>
    <input type="color" data-behavior="color_picker" class="color_picker" />
    <div class="brush_size_label_and_range">
      <label for="brush_size">Brush Size</label>
      <input type="range" data-behavior="brush_size_tool" min="1" max="5" step=".5" id="brush_size" value="1" />
    </div>
    <%= link_to "Eraser", "", class: "btn", data: { behavior: "erase_tool" } %>
    <%= link_to "Erase All", "", class: "btn", data: { behavior: "erase_all_tool" } %>
    <%= link_to "Save", "", class: "btn", remote: true, data: { behavior: "save_tool", url: whiteboard_path(@whiteboard) } %>
</div>
<div class="center">
  <canvas data-url="<%= @whiteboard.canvas.url %>" data-channel="<%= @whiteboard.channel_name %>">
    Your browser does not support HTML5.  Please use the latest version of Google Chrome, Safari, FireFox, or use Internet Explorer 6+ with the free Google Chrome Plugin, which can be downloaded <%= link_to "here", "http://www.google.com/chromeframe" %>.
  </canvas>
</div>