config/routes.rb
Whiteboard::Application.routes.draw do
  root to: 'homes#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :customers, only: %w[new create]
  resources :plans, only: %w[index]
  resources :subscriptions, only: %w[create destroy]
  resources :whiteboards, only: %w[index create update show]
  resources :pusher, only: %w[] do
    collection { post :auth }
  end
  resource :subscribers, only: %w[show] do
    collection { post :add_user }
  end
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  has_many :users, dependent: :destroy
  has_one  :subscription, dependent: :destroy

  def trial?
    ((Time.now - created_at.to_time) < 1.month.to_i) && subscription.try(:plan_id) == 1
  end

  def days_left_in_trial
    ((1.month.to_i - (Time.now - created_at.to_time)) / 1.day.to_i).round
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_filter :authenticate_subscriber!

  def show
    @subscriber = current_user.subscriber
    @users = @subscriber.users
    @subscription = @subscriber.subscription
    @whiteboards = @subscription.drawings if @subscription
    @user = User.new
    flash.now[:notice] = "Your account admin will be able to change plans, update billing info, and delete your subscription from here." unless current_user.customer?
  end

  def add_user
    @subscriber = current_user.subscriber
    @user = @subscriber.users.new(params[:user])

    if @user.save
      flash[:notice] = "User added."
    else
      flash[:alert] = @user.errors.full_messages.first
    end
    redirect_to subscribers_url
  end
end

app/views/subscribers/_user.html.erb
<% cache user do %>
  <li class="large-font">
    <%= user.email %>
    <% if user.customer? %>
      <span class="label label-info">Account Admin</span>
    <% end %>
  </li>
<% end %>

app/views/subscribers/show.html.erb
<% if @subscriber.trial? %>
  <div class="alert alert-success">
    <p class="center">You have <b><%= @subscriber.days_left_in_trial %> days</b> left in your trial. You will be automatically upgraded to a starter plan when your trial expires.</p>
  </div>
<% end %>
<div class="page-header">
  <h1 class="center">
    <% if @subscription.present? %>
      Subscribed to: <%= @subscription.plan_name %> Plan
    <% else %>
      Subscribed to: <b>None</b>
    <% end %>
    <% if current_user.customer? %>
      <%= link_to "Change", plans_path, class: "btn-mini btn-info vert-middle"  %>
      <%= link_to "Update Billing Info", new_customer_path, class: "btn-mini btn-success vert-middle", data: { "no-turbolink" => true } %>
      <%= link_to "Delete", subscription_path(@subscription), data: { "no-turbolink" => true, confirm: "Are you sure?  You will lose all subscription data!  This action can not be reversed!", disable_with: "Cancelling..." }, method: :delete, class: "btn-mini btn-primary inline vert-middle" if @subscription.present? %>
    <% end %>
  </h1>
</div>
<div class="row-fluid mb30">
  <div class="span6 hero-unit">
    <h2><%= pluralize @users.size, "User" %></h2>
    <p class="lead">Your plan allows for up to <%= @subscription.try(:plan_allowed_users) || 0 %> users.</p>
    <div class="pop_up_form">
    <h2 class="ml15">Add User</h2>
    <%= form_for @user, url: add_user_subscribers_url do |f| %>
      <div class="input-prepend inline mr5">
        <span class="add-on"><i class="icon-envelope"></i></span><%= f.email_field :email, class: "input-small", placeholder: "Email" %>
        <span class="add-on"><i class="icon-lock"></i></span><%= f.password_field :password, class: "input-small", placeholder: "Password" %>
      </div>
      <%= f.submit "Add", data: { disable_with: "Adding..."}, class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="mt15">
    <ul>
      <% cache @users do %>
        <%= render partial: "subscribers/user", collection: @users %>
      <% end %>
    </ul>
  </div>
  </div>
  <div class="span6 hero-unit">
    <% if @subscription.present? %>
      <h2><%= pluralize @whiteboards.size, "Whiteboard" %></h2>
      <p class="lead">Your plan allows for up to <%= @subscription.plan_allowed_whiteboards %> whiteboards.</p>
    <% end %>
  </div>
</div>