config/routes.rb
Whiteboard::Application.routes.draw do
  root to: 'homes#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :customers, only: %w[new create]
  resources :plans, only: %w[index]
  resources :subscriptions, only: %w[create destroy]
  resources :whiteboards, only: %w[index create update show]
  resources :pusher, only: %w[] do
    collection { post :auth }
  end
  resource :subscribers, only: %w[show] do
    collection { post :add_user }
  end
end

app/views/layouts/_flash_messages.html.erb
<%- if flash[:alert].present? -%>
  <div class="alert alert-warning">
    <button class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %>
  </div>
<%- elsif flash[:notice].present? -%>
  <div class="alert alert-info">
    <button class="close" data-dismiss="alert">×</button>
    <%= flash[:notice] %>
  </div>
<%- end -%>

<%- if flash[:analytics].present? -%>
  <script type="text/javascript">
    _gaq.push(['_trackPageview', '<%= flash[:analytics] %>']);
  </script>
<%- end -%>

<%- browser = Browser.new(ua: request.env['HTTP_USER_AGENT'], accept_language: "en-us") -%>
<%- if browser.ie? -%>
  <div class="alert alert-warning">
    <button class="close" data-dismiss="alert">×</button>
    <span>Hello Internet Explorer user,</span>
    <p><b>Whiteboard works best with Chrome, FireFox, or Safari.</b>  All three are available for FREE and take less than 5 minutes to install. <b>Internet Explorer does not support the cutting edge features that Whiteboard implements to give you the best possible experience.</b> Please consider switching browsers. You will be amazed at how much better every website will look and work for you.  If you must stick with Internet Explorer, please consider installing Google's Chrome Frame plugin available for FREE.</p>
  </div>
<%- end -%>

app/views/layouts/_nav_bar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "WhiteBoard", root_path, class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <%- if current_user.try(:subscriber) -%>
            <li><%= link_to "Whiteboards <i class='icon-th-large icon-white'></i>".html_safe, whiteboards_path %></li>
            <li><%= link_to "Manage <i class='icon-list-alt icon-white'></i>".html_safe, subscribers_path %></li>
          <%- else -%>
            <li><%= link_to "Pricing <i class='icon-tag icon-white'></i>".html_safe, plans_path %></li>
          <%- end -%>
        </ul>
        <ul class="nav pull-right">
          <li><a href="javascript:UserVoice.showPopupWidget();" title="Support">Support <i class='icon-wrench icon-white'></i></a></li>
          <%- if current_user -%>
            <li><%= link_to "My Account <i class='icon-user icon-white'></i>".html_safe, edit_user_registration_path %></li>
            <li><%= link_to "Sign Out <i class='icon-off icon-white'></i>".html_safe, destroy_user_session_path, method: :delete, data: { "no-turbolink" => true, disable_with: "Signing Out..." } %></li>
          <%- else -%>
            <li><%= link_to "Sign In <i class='icon-off icon-white'></i>".html_safe, new_user_session_path %></li>
          <%- end -%>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhiteBoard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "http://js.pusher.com/1.12/pusher.min.js", "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: "description", content: "WhiteBoard allows realtime collaboration. Conduct meetings remotely and have up to 125 people view and add changes at the same time!" %>
  <%= tag :meta, name: "stripe-key", content: STRIPE_PUBLIC_KEY %>
  <%= tag :meta, name: "pusher-key", content: PUSHER_PUBLIC_KEY %>
  <meta name="apple-mobile-web-app-capable" content="yes" />
</head>
<body>
  <%= render "layouts/nav_bar" %>
  <div class="container">
    <%= render "layouts/flash_messages" %>
    <%= yield %>
  </div>
  <%= javascript_include_tag "uservoice" %>
</body>
</html>